### ISSUE TITLE
Exception on Rider 2020.3.3

### ISSUE THREAD

**Issue by guneyozsan** [weisJ/auto-dark-mode#30]
I started getting an exception on Rider 2020.3.3. It started after the plugin is updated. It happens immediately on app launch.

````
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/github/weisj/darkmode/platform/AbstractThemeMonitor
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: com/github/weisj/darkmode/platform/AbstractThemeMonitor
	at com.github.weisj.darkmode.AutoDarkMode.createMonitor(AutoDarkMode.kt:50)
	at com.github.weisj.darkmode.AutoDarkMode.access$createMonitor(AutoDarkMode.kt:43)
	at com.github.weisj.darkmode.AutoDarkMode$monitor$1.invoke(AutoDarkMode.kt:45)
	at com.github.weisj.darkmode.AutoDarkMode$monitor$1.invoke(AutoDarkMode.kt:43)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.github.weisj.darkmode.platform.settings.UtilKt.letValue(Util.kt:49)
	at com.github.weisj.darkmode.AutoDarkMode.start(AutoDarkMode.kt:58)
	at com.github.weisj.darkmode.AutoDarkModeStartupListener.appFrameCreated(AutoDarkModeStartupListener.kt:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:656)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:401)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:383)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:189)
	at com.sun.proxy.$Proxy37.appFrameCreated(Unknown Source)
	at com.intellij.idea.IdeStarter.main(IdeStarter.kt:104)
	at com.intellij.idea.ApplicationLoader$startApp$8.run(ApplicationLoader.kt:239)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
	... 11 more
Caused by: java.lang.ClassNotFoundException: com.github.weisj.darkmode.platform.AbstractThemeMonitor PluginClassLoader[PluginDescriptor(name=Auto Dark Mode, id=com.github.weisj.darkmode, path=C:\Users\guney\AppData\Roaming\JetBrains\Rider2020.3\plugins\auto-dark-mode-plugin, version=1.5.2-2020.3)] com.intellij.ide.plugins.cl.PluginClassLoader@6de0ce92
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:129)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 33 more

JetBrains Rider 2020.3.3
Build #RD-203.7148.23, built on February 17, 2021
Licensed to Rider Evaluator
Expiration date: April 3, 2021
Runtime version: 11.0.9.1+11-b1145.63 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
.NET Framework 4.0.30319.42000
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1450M
Cores: 8
Registry: debugger.new.debug.tool.window.view=true, ide.tree.horizontal.default.autoscrolling=false, performance.watcher.sampling.interval.ms=200, ide.borderless.tab.caption.in.title=false, ide.tooltip.showAllSeverities=true, show.diff.preview.as.editor.tab=true, ide.mac.bigsur.alerts.enabled=false, debugger.show.values.use.inlays=false, light.edit.file.open.enabled=false, performance.watcher.unresponsive.interval.ms=1000, search.everywhere.settings=true, show.diff.preview.as.editor.tab.with.single.click=true, parameter.info.max.visible.rows=10, ide.win.file.chooser.native=true, vcs.log.show.diff.preview.as.editor.tab=true, search.everywhere.pattern.checking=false, ide.tooltip.initialDelay=0, ide.mac.bigsur.window.with.tabs.enabled=false, ide.require.transaction.for.model.changes=false, ide.debug.in.title=true, rdclient.asyncActions=false, ide.new.project.model=false
Non-Bundled Plugins: com.github.weisj.darkmode
````

**Comment by weisJ** [comment]
How did you install the update? It looks like the `1.5.2-2020.3` jar is used as an entry point while the other jars are from the updated `1.5.3-2020.3` version.

**Comment by guneyozsan** [comment]
I updated via the update pop-up. I just clicked update.
![image](https://user-images.githubusercontent.com/19275187/111363533-390de280-86a1-11eb-84ef-1e305070c7f8.png)
![image](https://user-images.githubusercontent.com/19275187/111363659-5cd12880-86a1-11eb-9ba0-4fed287148ae.png)

It didn't happen on my other PC. But this one still gives error on every launch.

I noticed after your note that it mentions 1.5.2-2020.3 in the title of the error dialog. I'll try removing and re-installing the plugin but I can wait if you need any feedback as it does not block anything.

**Comment by weisJ** [comment]
If there wasn't any error with other IDEs/on another PC then there probably isn't a direct problem with the plugin itself. I will report this issue to JetBrains as this may be an issue with the plugin update process. Fell free to reinstall the plugin and see whether that solves the issue.

**Comment by guneyozsan** [comment]
Reinstalling was fine. Thanks!
