### ISSUE TITLE
Exception repeatedly happens on M1 macOS

### ISSUE THREAD

**Issue by blargism** [weisJ/auto-dark-mode#36]
Exception throws every time I start DataGrip. I believe it works on my other JetBrains IDEs.

OS: macOS Big Sur 11.4
Arch: Apple M1

```
Could not load library libauto-dark-mode-macos.dylib.

java.lang.UnsatisfiedLinkError: /private/var/folders/m6/51kww85d01s9s1dwdrx_51880000gn/T/nativeutils232039527520916/libauto-dark-mode-macos.dylib: dlopen(/private/var/folders/m6/51kww85d01s9s1dwdrx_51880000gn/T/nativeutils232039527520916/libauto-dark-mode-macos.dylib, 1): no suitable image found.  Did find:
	/private/var/folders/m6/51kww85d01s9s1dwdrx_51880000gn/T/nativeutils232039527520916/libauto-dark-mode-macos.dylib: mach-o, but wrong architecture
	/private/var/folders/m6/51kww85d01s9s1dwdrx_51880000gn/T/nativeutils232039527520916/libauto-dark-mode-macos.dylib: mach-o, but wrong architecture
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.github.weisj.darklaf.platform.NativeUtil.loadLibraryFromJar(NativeUtil.java:104)
	at com.github.weisj.darklaf.platform.AbstractLibrary.loadLibrary(AbstractLibrary.java:65)
	at com.github.weisj.darklaf.platform.AbstractLibrary.updateLibrary(AbstractLibrary.java:53)
	at com.github.weisj.darkmode.platform.macos.MacOSLibrary.get(MacOSLibrary.java:39)
	at com.github.weisj.darkmode.platform.macos.MacOSThemeMonitorService.isSupported(MacOSThemeMonitorService.kt:37)
	at com.github.weisj.darkmode.platform.ThemeMonitorImpl.<init>(ThemeMonitorImpl.kt:46)
	at com.github.weisj.darkmode.AutoDarkMode.createMonitor(AutoDarkMode.kt:49)
	at com.github.weisj.darkmode.AutoDarkMode.access$createMonitor(AutoDarkMode.kt:43)
	at com.github.weisj.darkmode.AutoDarkMode$monitor$1.invoke(AutoDarkMode.kt:45)
	at com.github.weisj.darkmode.AutoDarkMode$monitor$1.invoke(AutoDarkMode.kt:43)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.github.weisj.darkmode.platform.settings.UtilKt.letValue(Util.kt:49)
	at com.github.weisj.darkmode.AutoDarkMode.start(AutoDarkMode.kt:56)
	at com.github.weisj.darkmode.AutoDarkModeStartupListener.appFrameCreated(AutoDarkModeStartupListener.kt:34)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:674)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:653)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:422)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:397)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:379)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:185)
	at com.sun.proxy.$Proxy35.appFrameCreated(Unknown Source)
	at com.intellij.idea.IdeStarter.main(IdeStarter.kt:101)
	at com.intellij.idea.ApplicationLoader$startApp$8.run(ApplicationLoader.kt:237)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at com.intellij.idea.ApplicationLoader$startApp$nonEdtExecutor$1.execute(ApplicationLoader.kt:135)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1069)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1742)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by weisJ** [comment]
This plugin currently doesn’t support the M1 architecture. For M1 I would recommend to use the built-in functionality of IDEA instead as it might take some time before I’m able to fix this issue.
