### ISSUE TITLE
Doesn't work on android studio, osx m1 monterey (works on Idea on the same mac)

### ISSUE THREAD

**Issue by Liverm0r** [weisJ/auto-dark-mode#48]
On android studio (AS) there is an error on AS startup. 

```bash
Could not load library libauto-dark-mode-macos.dylib.

java.lang.UnsatisfiedLinkError: /private/var/folders/1c/2jwn_cdx3hs1w57c_xg3yz5w0000gn/T/nativeutils50706038885166/libauto-dark-mode-macos.dylib: dlopen(/private/var/folders/1c/2jwn_cdx3hs1w57c_xg3yz5w0000gn/T/nativeutils50706038885166/libauto-dark-mode-macos.dylib, 0x0001): tried: '/private/var/folders/1c/2jwn_cdx3hs1w57c_xg3yz5w0000gn/T/nativeutils50706038885166/libauto-dark-mode-macos.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/libauto-dark-mode-macos.dylib' (no such file), '/usr/lib/libauto-dark-mode-macos.dylib' (no such file)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.github.weisj.darklaf.platform.NativeUtil.loadLibraryFromJar(NativeUtil.java:104)
	at com.github.weisj.darklaf.platform.AbstractLibrary.loadLibrary(AbstractLibrary.java:65)
	at com.github.weisj.darklaf.platform.AbstractLibrary.updateLibrary(AbstractLibrary.java:53)
	at com.github.weisj.darkmode.platform.macos.MacOSLibrary.get(MacOSLibrary.java:39)
	at com.github.weisj.darkmode.platform.macos.MacOSThemeMonitorService.isSupported(MacOSThemeMonitorService.kt:37)
	at com.github.weisj.darkmode.platform.ThemeMonitorImpl.<init>(ThemeMonitorImpl.kt:46)
	at com.github.weisj.darkmode.AutoDarkMode.createMonitor(AutoDarkMode.kt:49)
	at com.github.weisj.darkmode.AutoDarkMode.access$createMonitor(AutoDarkMode.kt:43)
	at com.github.weisj.darkmode.AutoDarkMode$monitor$1.invoke(AutoDarkMode.kt:45)
	at com.github.weisj.darkmode.AutoDarkMode$monitor$1.invoke(AutoDarkMode.kt:43)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.github.weisj.darkmode.platform.settings.UtilKt.letValue(Util.kt:49)
	at com.github.weisj.darkmode.AutoDarkMode.start(AutoDarkMode.kt:56)
	at com.github.weisj.darkmode.AutoDarkModeStartupListener.appFrameCreated(AutoDarkModeStartupListener.kt:34)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:674)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:653)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:422)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:397)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:379)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:185)
	at com.sun.proxy.$Proxy51.appFrameCreated(Unknown Source)
	at com.intellij.idea.IdeStarter.main(IdeStarter.kt:101)
	at com.intellij.idea.ApplicationLoader$startApp$8.run(ApplicationLoader.kt:237)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
````

**Comment by Liverm0r** [comment]
Seems like some modules are not compiles for m1, but how does it work on Iterllij Idea?
https://apple.stackexchange.com/questions/436801/m1-mac-mach-o-file-but-is-an-incompatible-architecture-have-x86-64-need-a

**Comment by Liverm0r** [comment]
1.6.1-2021.3 on Idea;
1.5.4-2021.1 on AS.

**Comment by weisJ** [comment]
Please try the following version:
[auto-dark-mode-plugin-1.6.2-2021.1-alpha.zip](https://github.com/weisJ/auto-dark-mode/files/8381133/auto-dark-mode-plugin-1.6.2-2021.1-alpha.zip)

**Comment by Liverm0r** [comment]
Yes, it works. Thank you very mutch!

**Comment by weisJ** [comment]
I have published the new version. Should be up in a couple of days.
