### ISSUE TITLE
libauto-dark-mode-linux-gtk.so not found

### ISSUE THREAD

**Issue by humblebeee** [weisJ/auto-dark-mode#55]
Hi,

I just updated to the latest version on my PyCharm and after a re-launch, I face this error:

```
.
.
.
2022-05-10 16:16:42,921 [   5485] SEVERE - #c.g.w.d.p.l.g.GtkLibrary - Could not load library libauto-dark-mode-linux-gtk.so.
java.io.FileNotFoundException: File /com/github/weisj/darkmode/auto-dark-mode-linux-gtk/linux-x86-64/libauto-dark-mode-linux-gtk.so was not found inside JAR.
	at com.github.weisj.darklaf.platform.NativeUtil.extractFile(NativeUtil.java:153)
	at com.github.weisj.darklaf.platform.NativeUtil.loadLibraryFromJar(NativeUtil.java:141)
	at com.github.weisj.darklaf.platform.NativeUtil.loadLibraryFromJarWithExtraResources(NativeUtil.java:87)
	at com.github.weisj.darklaf.platform.AbstractLibrary.loadLibrary(AbstractLibrary.java:62)
	at com.github.weisj.darklaf.platform.AbstractLibrary.updateLibrary(AbstractLibrary.java:50)
	at com.github.weisj.darkmode.platform.linux.gtk.GtkLibrary.get(GtkLibrary.java:39)
	at com.github.weisj.darkmode.platform.linux.gtk.GtkSettings.<clinit>(GtkSettings.kt:86)
	at com.github.weisj.darkmode.platform.linux.gtk.GtkSettingsProvider$1.invoke(GtkSettings.kt:34)
	at com.github.weisj.darkmode.platform.linux.gtk.GtkSettingsProvider$1.invoke(GtkSettings.kt:34)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.github.weisj.darkmode.platform.settings.SingletonSettingsContainerProvider.getContainer(Settings.kt:42)
	at com.github.weisj.darkmode.platform.settings.SingletonSettingsContainerProvider.create(Settings.kt:43)
	at com.github.weisj.darkmode.AutoDarkModeOptions$containers$2$2.invoke(AutoDarkModeOptions.kt:70)
	at com.github.weisj.darkmode.AutoDarkModeOptions$containers$2$2.invoke(AutoDarkModeOptions.kt:70)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
	at com.github.weisj.darkmode.AutoDarkModeOptions$containers$2.invoke(AutoDarkModeOptions.kt:72)
	at com.github.weisj.darkmode.AutoDarkModeOptions$containers$2.invoke(AutoDarkModeOptions.kt:66)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.github.weisj.darkmode.AutoDarkModeOptions.getContainers(AutoDarkModeOptions.kt:66)
	at com.github.weisj.darkmode.AutoDarkModeOptions$properties$2.invoke(AutoDarkModeOptions.kt:75)
	at com.github.weisj.darkmode.AutoDarkModeOptions$properties$2.invoke(AutoDarkModeOptions.kt:74)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.github.weisj.darkmode.AutoDarkModeOptions.getProperties(AutoDarkModeOptions.kt:74)
	at com.github.weisj.darkmode.AutoDarkModeOptions.loadState(AutoDarkModeOptions.kt:135)
	at com.github.weisj.darkmode.AutoDarkModeOptions.loadState(AutoDarkModeOptions.kt:39)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:441)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:373)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:119)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:48)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:536)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:55)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:610)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:584)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.github.weisj.darkmode.AutoDarkMode.<clinit>(AutoDarkMode.kt:126)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:891)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:610)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:584)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.github.weisj.darkmode.AutoDarkModeStartupListener.appFrameCreated(AutoDarkModeStartupListener.kt:33)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:642)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:621)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:391)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:373)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:34)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:180)
	at com.sun.proxy.$Proxy35.appFrameCreated(Unknown Source)
	at com.intellij.idea.IdeStarter.openProjectIfNeeded(IdeStarter.kt:98)
	at com.intellij.idea.IdeStarter.main(IdeStarter.kt:79)
	at com.intellij.idea.ApplicationLoader$initApplication$4.accept(ApplicationLoader.kt:176)
	at com.intellij.idea.ApplicationLoader$initApplication$4.accept(ApplicationLoader.kt)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1742)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2022-05-10 16:16:42,977 [   5541] SEVERE - #c.g.w.d.p.l.g.GtkLibrary - PyCharm 2022.1  Build #PC-221.5080.212
2022-05-10 16:16:42,981 [   5545] SEVERE - #c.g.w.d.p.l.g.GtkLibrary - JDK: 11.0.14.1; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-05-10 16:16:43,003 [   5567] SEVERE - #c.g.w.d.p.l.g.GtkLibrary - OS: Linux
2022-05-10 16:16:43,006 [   5570] SEVERE - #c.g.w.d.p.l.g.GtkLibrary - Plugin to blame: Auto Dark Mode version: 1.7.0-2022.1
```

Distro: Fedora 35

**Comment by weisJ** [comment]
Sorry for the inconvenience. Somehow the build got corrupted. I have removed the faulty version and resubmitted a fixed build.

**Comment by humblebeee** [comment]
Thank you! Can confirm it's all good now!
