### ISSUE TITLE
Illegal State Exception on macOS 10.15.5

### ISSUE THREAD

**Issue by linderd** [weisJ/auto-dark-mode#6]
- OS: macOS 10.15.5
- IDE: CLion 2020.1.1
- Default Java: 11.0.2
- auto-dark-mode Version: 1.2.0

Hi, 
I get an Illegal State Exception for auto-dark-mode when I start CLion. I tried to update everything to the newest version, didn't help. I think it happens since the update to auto-dark-mode 1.2.0, but could also be since the new macOS-update.
Here is the stacktrace:
~~~~
java.lang.IllegalStateException: Could not load library.
	at com.github.weisj.darkmode.platform.AbstractThemeMonitor.<init>(AbstractThemeMonitor.java:22)
	at com.github.weisj.darkmode.AutoDarkMode.createMonitor(AutoDarkMode.java:32)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at com.github.weisj.darkmode.AutoDarkMode.start(AutoDarkMode.java:41)
	at com.github.weisj.darkmode.AutoDarkModeStartupListener.appFrameCreated(AutoDarkModeStartupListener.java:14)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:546)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:139)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:465)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:415)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:397)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$3(MessageBusImpl.java:237)
	at com.sun.proxy.$Proxy40.appFrameCreated(Unknown Source)
	at com.intellij.idea.IdeStarter.main(IdeStarter.kt:103)
	at com.intellij.idea.ApplicationLoader$startApp$8.run(ApplicationLoader.kt:222)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
~~~~

**Comment by weisJ** [comment]
Thank you for reporting! Seems like there is a path misconfiguration after switching the build system. I have adjusted the path and released a fix.  It will take ~2 days until the patch is available.

**Comment by weisJ** [comment]
Patch is live now! @linderd could you confirm that it’s working now for you?

**Comment by linderd** [comment]
Checked it up, yes it works like a charm now. Thank you very much 👍
